name: DockerHub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - 'main'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ansible:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/ansible:latest
          ghcr.io/${{ github.repository_owner }}/ansible:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/ansible:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
